os: linux
dist: focal
language: node_js
node_js:
  - 18
cache: npm

install:
  - "npm install npm@9 --global"
  - "npm ci --prefix ./frontend --force"

script:
  - "cd frontend/"
  - "npx eslint -c .eslintrc.js ./**/*.js ./**/*.jsx"
