dist: focal
sudo: true
language: node_js
node_js:
  - 18
install:
  - "npm install --prefix ./frontend"
services: mysql
addons:
  chrome: stable


before_install:
  - "npm install npm@9 --global"
  - sudo mysql -e 'DROP DATABASE IF EXISTS flask_test_mysql_db'
  - sudo mysql -e "CREATE DATABASE IF NOT EXISTS flask_test_mysql_db"
  - sudo mysql -u root --default-character-set=utf8 flask_test_mysql_db < backend/db_schemas_for_test/comment_post.sql

script:
  - "npm start"

jobs:
  include:
    - language: python
      python: 3.9
      before_script:
        - "pip install -r ./backend/requirements.txt"
        - "chmod 0777 ./backend/tests/selenium_tests.py"
      script:
        - "python backend/tests/selenium_tests.py"