os: linux
dist: focal
language: node_js
node_js:
  - 18
cache: npm

install:
  - "npm install --prefix ./frontend --force"
services: mysql
addons:
  chrome: stable


before_install:
  - "npm install npm@9 --global"
  - sudo mysql -e 'DROP DATABASE IF EXISTS flask_test_mysql_db'
  - sudo mysql -e "CREATE DATABASE IF NOT EXISTS flask_test_mysql_db"
  - sudo mysql -u root --default-character-set=utf8 flask_test_mysql_db < backend/"db schemas for test"/comment_post.sql
  - "google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
before_script:
  - "npm run build --prefix ./frontend"
  - "sleep 10"

script:
  - "npm start --prefix ./frontend"
  - "sleep 10"

jobs:
  include:
    - language: python
      python: 3.9
      cache: pip
      before_script:
        - "pip install -r ./backend/requirements.txt"
        - "chmod 0777 ./backend/tests/selenium_tests.py"
