os: linux
dist: focal
language: node_js
node_js:
  - 18
cache: npm

install:
  - "npm ci --prefix ./frontend --force"

script:
  - "npx eslint -c ./frontend/.eslintrc ./frontend/**/*.js ./frontend/**/*.jsx"
